using Test
include("test_linear.jl")
include("simple_continuation.jl")
include("test_newton.jl")
include("test-cont-non-vector.jl")
include("testJacobianFoldDeflation.jl")
include("testHopfMA.jl")
include("test_ms.jl")
include("test_potrap.jl")
include("test-bordered-problem.jl")
