using Test
include("test_ms.jl")
include("poincareMap.jl")
include("testNF.jl")
include("stuartLandauSH.jl")
include("test_linear.jl")
include("simple_continuation.jl")
include("test_newton.jl")
include("test_bif_detection.jl")
include("test-cont-non-vector.jl")
include("testJacobianFoldDeflation.jl")
include("testHopfMA.jl")
include("test_potrap.jl")
include("test-bordered-problem.jl")
include("precond.jl")
